cuba progress indicator
cuba-elements/cuba-ui pull request #2
Opened 2018-05-18 13:50 UTC by JakovRus

2018-05-18 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cuba-elements/cuba-ui?pullRequest=2) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cuba-elements/cuba-ui?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cuba-elements/cuba-ui?pullRequest=2) it.</sub>

2018-05-19 09:48 UTC, jreznot commented
Please sign CLA before we review and merge this

2018-05-21 07:32 UTC, web-devel commented on cuba-progress-indicator.html
> +          document.body.removeEventListener('cuba-data-loading-start', this._incrementCounter.bind(this));
It's not the same listener

2018-05-21 08:48 UTC, web-devel commented on cuba-progress-indicator.html
> +        background-color: var(--progress-color, #0040a8);
Describe vars in comments

2018-05-21 10:36 UTC, web-devel requested changes

2018-05-21 10:36 UTC, web-devel commented on cuba-progress-indicator.html
> +       *  `<cuba-progress-indicator>` is a Polymer 2 element for data loading progress indication.
So we have to remove Polymer 1 from version range in `bower.json`.

2018-05-22 11:34 UTC, merged